image: docker

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: devops

build:
  stage: build
  before_script:
    - mkdir .docker
  script:
    - docker-compose build
    - docker image ls
    - docker save -o .docker/devops-nginx.tar devops-nginx:latest
    - docker save -o .docker/devops-service1.tar devops-service1:latest
    - docker save -o .docker/devops-service2.tar devops-service2:latest
    - docker save -o .docker/devops-shutdown.tar devops-shutdown:latest
  artifacts:
    paths:
      - .docker/

test:
  stage: test
  before_script:
    - docker load -q -i .docker/devops-nginx.tar
    - docker load -q -i .docker/devops-service1.tar
    - docker load -q -i .docker/devops-service2.tar
    - docker load -q -i .docker/devops-shutdown.tar
  script:
    - echo "Test phase initiated"
    - apk add --no-cache python3 py3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install requests pytest
    - docker-compose build
    - pytest tests.py

deploy:
  stage: deploy
  script:
    - echo "Deploy phase mock"
