variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

services:
  - name: docker:20.10.16-dind
    command: ["--privileged"]

test:
  image: docker:latest
  services:
    - docker:dind # this starts another container in the pod which results in the docker daemon "proxy" exposed in the pod's network namespace on 2375
  script:
    - docker ps
