image: docker

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

#Verifying that a build is successful
build:
  stage: build
  script:
    - docker-compose build
    - docker image ls
    - docker ps

#Running tests on a built project
#I could not get the build passed on as artifacts due to limited size.
#Learned that Gitlab admins could increase the size, but I don't have access to that.
#There might be a smarter way related to mounting volumes, but I couldn't do it.
#I decided to continue with knowing my limitations. The result is a slowed down operation,
#and the build stage might be redundant.
test:
  stage: test
  before_script:
    - echo "Dependencies for python testing"
    - apk add --no-cache python3 py3-pip
    - pip install requests pytest
  script:
    - echo "Test phase initiated"
    - docker-compose up --build -d
    - docker ps
    - pytest tests.py

deploy:
  stage: deploy
  script:
    - echo "Deploy phase mock"
