services:
  service1:
    build:
      context: ./jsWS
      dockerfile: Dockerfile.service1
    depends_on:
      - service2
    environment:
      - PORT=8199
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  service2:
    build:
      context: ./pythonWS
      dockerfile: Dockerfile.service2
    environment:
      - PORT=8200
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    ports:
      - "8198:8081"
      - "8197:8197"
    networks:
      - loadbalancing
    depends_on:
      - service1
      - service2
      - api_gateway

  shutdown:
    build:
      context: .
      dockerfile: shutdown/Dockerfile.shutdown
    environment:
      - PORT=5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - loadbalancing
    privileged: true

  api_gateway:
    build: 
      context: ./state_api
      dockerfile: Dockerfile.api_gateway
    ports:
      - "8197:8197"
    networks:
      - loadbalancing
    privileged: true

networks:
  loadbalancing:
