

upstream service1 {
    server service1:8199;
}
upstream shutdown {
    server shutdown:5000;
}

server {
    listen 8081;

    resolver 127.0.0.11 valid=5s;

    include /etc/nginx/mime.types;

    location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        root /usr/share/nginx/html;
        index index.html;
    }

    location /service1 {
        proxy_pass http://service1/;
    }

    location /shutdown {
        proxy_pass http://shutdown/shutdown;
    }

    location = /401.html {
        root /usr/share/nginx/html;
    }
}
