

upstream service1 {
    server service1:8199;
}

server {
    listen 8081;

    resolver 127.0.0.11 valid=5s;

    include /etc/nginx/mime.types;

    location / {
        proxy_pass http://service1/;

    }
}
